services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: a2gbfljnb3jtcX5JSiw7
            MONGO_INITDB_DATABASE: the_database
        volumes:
            - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
            - pb_dev_mongo_data:/data_db
    server:
        build:
            context: ./backend
            dockerfile: dev.Dockerfile
        volumes:
            - ./backend:/usr/src/app
            - pb_dev_node_modules_be:/usr/src/app/node_modules
        environment:
            - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
            - PORT=3001
        container_name: phonebook-backend-dev
        depends_on:
            mongo:
                condition: service_started
                restart: true
    app:
        build:
            context: ./frontend
            dockerfile: dev.Dockerfile
        volumes:
            - ./frontend:/usr/src/app
            - pb_dev_node_modules_fe:/usr/src/app/node_modules
        environment:
            - VITE_BACKEND_URL=/api
        container_name: phonebook-frontend-dev
        depends_on:
            - server
    nginx:
        image: nginx:1.20.1
        volumes:
            - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 8080:80
        container_name: reverse-proxy-dev
        depends_on:
            - app
volumes:
    pb_dev_node_modules_fe:
    pb_dev_node_modules_be:
    pb_dev_mongo_data:
